/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BookingStatus = "cancelled" | "completed" | "confirmed";

export type EnrollmentStatus = "active" | "cancelled" | "completed" | "paused";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type RoomType = "classroom" | "practice" | "studio";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "instructor" | "user";

export interface CourseEnrollments {
  completedAt: Timestamp | null;
  courseId: number;
  createdAt: Generated<Timestamp | null>;
  enrolledAt: Generated<Timestamp | null>;
  id: Generated<number>;
  progressPercentage: Generated<number | null>;
  status: Generated<EnrollmentStatus>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface Courses {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  instructorId: number | null;
  isActive: Generated<boolean | null>;
  maxStudents: Generated<number | null>;
  name: string;
  price: Generated<Numeric | null>;
  skillLevel: Generated<string | null>;
  totalLessons: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Ebooks {
  courseId: number | null;
  coverImageUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  descriptionVi: string | null;
  fileUrl: string | null;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  sortOrder: Generated<number>;
  title: string;
  titleVi: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface LessonCompletions {
  completedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp | null>;
  enrollmentId: number;
  id: Generated<number>;
  lessonNumber: number;
  markedBy: number;
}

export interface LessonSchedules {
  createdAt: Generated<Timestamp | null>;
  enrollmentId: number;
  id: Generated<number>;
  lessonNumber: number;
  notification1hId: string | null;
  notification24hId: string | null;
  scheduledAt: Timestamp;
  updatedAt: Generated<Timestamp | null>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface RoomBookings {
  createdAt: Generated<Timestamp | null>;
  endTime: Timestamp;
  id: Generated<number>;
  notes: string | null;
  roomId: number;
  startTime: Timestamp;
  status: Generated<BookingStatus>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface Rooms {
  capacity: Generated<number>;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  equipment: string[] | null;
  hourlyRate: Generated<Numeric | null>;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  name: string;
  roomType: Generated<RoomType>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface UserProfiles {
  address: string | null;
  bankAccountName: string | null;
  bankAccountNumber: string | null;
  bankName: string | null;
  createdAt: Generated<Timestamp | null>;
  dateOfBirth: Timestamp | null;
  fullName: string | null;
  gender: string | null;
  id: Generated<number>;
  phoneNumber: string | null;
  preferredPaymentMethod: string | null;
  registrationCompleted: Generated<boolean | null>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
  whatsappNumber: string | null;
}

export interface DB {
  courseEnrollments: CourseEnrollments;
  courses: Courses;
  ebooks: Ebooks;
  lessonCompletions: LessonCompletions;
  lessonSchedules: LessonSchedules;
  loginAttempts: LoginAttempts;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  roomBookings: RoomBookings;
  rooms: Rooms;
  sessions: Sessions;
  userPasswords: UserPasswords;
  userProfiles: UserProfiles;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","instructor","user"];
export const RoomTypeArrayValues: [RoomType, ...RoomType[]] = ["classroom","practice","studio"];
export const EnrollmentStatusArrayValues: [EnrollmentStatus, ...EnrollmentStatus[]] = ["active","cancelled","completed","paused"];
export const BookingStatusArrayValues: [BookingStatus, ...BookingStatus[]] = ["cancelled","completed","confirmed"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.